# Generated by Django 5.0.4 on 2024-05-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrupt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbankrupt',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
