# Generated by Django 5.0.4 on 2024-05-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankrupt_app', '0002_isbankrupt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbankrupt',
            name='status',
        ),
    ]
