# Generated by Django 5.0.4 on 2024-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_brand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('-name',)},
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
