# Generated by Django 5.0.4 on 2024-05-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_brand_options_brand_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
    ]
