# Generated by Django 5.0.4 on 2024-05-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_brand_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='category',
        ),
    ]
