# Generated by Django 5.0.6 on 2024-06-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_details', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
