# Generated by Django 5.0.6 on 2024-06-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_date',
            new_name='task_assign_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_details',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='task_title',
        ),
    ]
